kind: pipeline
type: kubernetes
name: default

steps:
- name: push_to_quay
  image: plugins/docker
  settings:
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/hocs-mi-dashboards
    tags: ${DRONE_COMMIT_SHA}
    dockerfile: app/Dockerfile
  environment:
    DOCKER_PASSWORD:
      from_secret: QUAY_PASSWORD
    DOCKER_USERNAME: ukhomeofficedigital+hocs-mi-dashboards
  when:
    branch:
    - drone
    event:
    - push