
version: latest

autoscale:
  enabled: false

deployment:
  replicas: 1
  annotations:
    downscaler/downtime: "Mon-Sun 00:00-08:00 Europe/London,Mon-Sun 18:00-24:00 Europe/London"

keycloak:
  realm: https://sso-dev.notprod.homeoffice.gov.uk/auth/realms/hocs-notprod
  domain: sso-dev.notprod.homeoffice.gov.uk/

app:
  resources:
    limits:
      memory: 512Mi
    requests:
      memory: 512Mi
  env:
  - name: isNotProd
    value: "1"
  - name: transformation_db_name
    valueFrom:
      secretKeyRef:
        name: cs-mi-dev-transformation-rds
        key: db_name
        optional: false
  - name: transformation_db_host
    valueFrom:
      secretKeyRef:
        name: cs-mi-dev-transformation-rds
        key: endpoint
        optional: false
  - name: transformation_db_password
    valueFrom:
      secretKeyRef:
        name: cs-mi-dev-transformation-rds
        key: password
        optional: false
  - name: transformation_db_username
    valueFrom:
      secretKeyRef:
        name: cs-mi-dev-transformation-rds
        key: username
        optional: false
  - name: transformation_db_port
    valueFrom:
      secretKeyRef:
        name: cs-mi-dev-transformation-rds
        key: port
        optional: false
  - name: transformation_db_resource
    valueFrom:
      secretKeyRef:
        name: cs-mi-dev-transformation-rds
        key: resource_id
        optional: false

ingress:
  external:
    host: hocs-mi-dashboards.mi-dev.cs-notprod.homeoffice.gov.uk
  internal:
    enabled: true
    host: hocs-mi-dashboards.mi-dev.internal.cs-notprod.homeoffice.gov.uk
