name: 'Docker Build and push plotly image'
on:
  pull_request:
    types: [ closed ]

jobs:
  tests:
    uses: ./.github/workflows/test.yml
  build-and-push:
    needs: [tests]
    uses: UKHomeOffice/hocs-github-actions/.github/workflows/docker-build-tag.yml@v2
    with:
      images: 'quay.io/ukhomeofficedigital/hocs-mi-dashboards'
    secrets: inherit
